# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9abda6380938a859167bd7e5329db9f3e3cdc3adf9b3804cef2a1eee22ffc77725b191c5c7017955be4c2eb01ea95a75ef49cbd91bb34f38edf382c90bb7b034

test:
  secret_key_base: a5ed190a90c4e477f16b9d7b6e876911b0f087cbb3a40185e64c456e52fa8a4f7cf432ad43d454cca4417a43e7cb0e6055966538f04632d55dde6ddcd99483a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
